import { StyleProp, StyleSheet, TextStyle } from 'react-native';

const color = {
    primary: '#52A55D',
    normal: '#232323',
    inactiveBottom: '#EFEFF0',
    ribbon: '#FF5D5D',
    faintBlack: '#555555',
    backgroundGray: '#EDEDEA',
    faintGray: '#EEEEEE',
    gray: '#949494',
};

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        paddingTop: 20,
        flexDirection: 'column',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingTop: 40,
        width: '100%',
        marginBottom: 15,
    },
    cancelIcon: {
        width: 24,
        height: 24,
        marginLeft: -8,
    },
    greenLine: {
        width: '50%',
        height: 2,
        backgroundColor: color.primary,
    },
    grayLine: {
        width: '50%',
        height: 1,
        backgroundColor: color.faintGray,
    },
    hospitalContainer: {
        paddingTop: 20,
        display: 'flex',
        justifyContent: 'center',
        width: '100%',
        borderBottomWidth: 1,
        borderBottomColor: color.faintGray,
    },
    flexRow: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    middleContainer: {
        width: '100%',
        padding: 20,
        justifyContent: 'center',
    },
    grayButton: {
        paddingHorizontal: 10,
        height: 24,
        borderRadius: 500,
        backgroundColor: color.faintGray,
        marginLeft: 6,
    },
    foraRibbonIcon: {
        width: 14,
        height: 11,
        marginRight: 4,
    },
    InputContainer: {
        width: '92.2%',
        height: 179,
        borderRadius: 8,
        borderWidth: 1,
        paddingHorizontal: 13,
        marginHorizontal: 16,
        justifyContent: 'center',
    },
    InputStyles: {
        width: '100%',
        color: color.normal,
        fontSize: 15,
        lineHeight: 24,
        letterSpacing: -0.5,
        fontFamily: 'Pretendard',
        textAlign: 'left',
        textAlignVertical: 'top',
    },
    uploadButton: {
        width: 100,
        height: 35,
        marginRight: -25,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalContainer: {
        position: 'absolute',
        top: 360,
        left: 13,
        justifyContent: 'center',
        alignItems: 'center',
    },
    overlay: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)', // 흐림 효과를 위한 반투명 배경
    },
    contents: {
        paddingHorizontal: 16,
        paddingTop: 20,
        width: '100%',
    },
    photoUploadContainer: {
        flexDirection: 'row',
        marginBottom: 20,
        alignItems: 'flex-start',
    },
    photoPreview: {
        width: 70,
        height: 70,
        borderRadius: 12,
        backgroundColor: '#FFF',
        marginRight: 10,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: 'rgba(0, 0, 0, 0.15)',
        shadowOffset: {
            width: 0,
            height: 0,
        },
        shadowOpacity: 0.5,
        shadowRadius: 3,
        elevation: 2,
    },
    deleteIcon: {
        position: 'absolute',
        top: 0,
        right: 0,
        backgroundColor: 'rgba(255, 255, 255, 0.5)',
        borderRadius: 10,
        padding: 5,
    },
    categoryContainer: {
        flexDirection: 'row',
        justifyContent: 'flex-start',
    },
    categoryButton: {
        display: 'flex',
        width: 70,
        height: 33,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 500,
        backgroundColor: '#EEE',
        marginRight: 8,
    },
    selectedCategoryButton: {
        backgroundColor: '#52A55D',
    },
    titleContainer: {
        width: '99%',
        height: 48,
        flexDirection: 'column',
        marginBottom: 20,
        marginTop: 12,
    },
    titleBar: {
        width: '100%',
        height: 0,
        marginTop: 11,
        borderBottomWidth: 1,
        borderBottomColor: '#232323',
    },
    contentContainer: {
        width: '99%',
        height: 459,
        marginBottom: 20,
    },
    contentInput: {
        width: '100%',
        height: '100%',
        textAlignVertical: 'top',
        padding: 10,
    },
    bottomContainer: {
        flexDirection: 'column',
        alignItems: 'center',
        width: '100%',
        justifyContent: 'center',
        borderTopColor: color.faintGray,
        borderTopWidth: 1,
        paddingTop: 20,
        paddingBottom: 40,
    },
    chooseButton: {
        borderRadius: 44,
        borderWidth: 1,
        width: 69,
        height: 34,
        marginHorizontal: 5,
        justifyContent: 'center',
        alignItems: 'center',
    },
    cancelButtonContainer: {
        paddingHorizontal: 40,
        height: 60,
        alignContent: 'center',
        justifyContent: 'center',
        borderRadius: 10,
    },
    submitButtonContainer: {
        flex: 1,
        height: 60,
        alignContent: 'center',
        justifyContent: 'center',
        borderRadius: 10,
    },
    reviewActionContainer: {
        flexDirection: 'row',
        paddingHorizontal: 16,
        paddingTop: 10,
        borderTopColor: color.faintGray,
        borderTopWidth: 1,
        justifyContent: 'space-between',
        height: 115,
        width: '100%',
        gap: 10,
    },
    bottomCheckbox: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 20,
        width: '100%',
        justifyContent: 'center',
    },
    checkboxIcon: {
        width: 20,
        height: 20,
        marginRight: 5,
    },
});

export const text = {
    fontFamily: 'Pretendard',
    fontStyle: 'normal',
    titleText: {
        color: '#000',
        textAlign: 'center',
        fontSize: 18,
        fontWeight: '600',
        lineHeight: 22.4,
        letterSpacing: 0,
        flex: 1,
    },
    foraRibbonText: {
        color: color.ribbon,
        textAlign: 'left',
        fontSize: 14,
        fontWeight: '400',
        lineHeight: 19.6,
        letterSpacing: -0.5,
    },
    borderText: {
        color: color.normal,
        textAlign: 'center',
        fontSize: 20,
        fontWeight: '700',
        lineHeight: 28,
    },
    bordernormalText: {
        color: color.normal,
        textAlign: 'center',
        fontSize: 18,
        fontWeight: '700',
        lineHeight: 28,
    },
    normalText: {
        color: color.normal,
        textAlign: 'center',
        fontSize: 14,
        lineHeight: 22.4,
        letterSpacing: -0.5,
    },
    faintText: {
        color: color.gray,
        textAlign: 'center',
        fontSize: 14,
        lineHeight: 19.5,
        letterSpacing: -0.5,
    },
    clickText: {
        color: color.primary,
        textAlign: 'center',
        fontSize: 14,
        lineHeight: 19.5,
        letterSpacing: -0.5,
    },
    photoPreviewText: {
        color: '#555',
        fontSize: 14,
        fontWeight: '400',
        lineHeight: 19.6,
        letterSpacing: -0.7,
    },
    categoryButtonText: {
        color: '#232323',
        textAlign: 'center',
        fontSize: 16,
        fontWeight: '400',
        lineHeight: 22.4,
        letterSpacing: -0.8,
    },
    selectedCategoryButtonText: {
        color: '#FFF',
        textAlign: 'center',
        fontSize: 16,
        fontWeight: '600',
        lineHeight: 22.4,
        letterSpacing: -0.8,
    },
    contentTitleText: {
        marginTop: 13,
        color: '#949494',
        fontSize: 18,
        fontWeight: '600',
        lineHeight: 24,
    },
    contentText: {
        color: '#949494',
        fontSize: 18,
        fontWeight: '400',
        lineHeight: 26,
        letterSpacing: -0.9,
    },
    anonymousText: {
        color: '#949494',
        fontSize: 14,
        fontWeight: '400',
        lineHeight: 19.6,
        letterSpacing: -0.7,
    },
    buttonText: {
        fontSize: 18,
        fontWeight: '400',
        lineHeight: 19.6,
        letterSpacing: -0.7,
        marginLeft: 2,
        textAlign: 'center',
    },
} as {
    [key: string]: StyleProp<TextStyle>;
};
