import { StyleProp, StyleSheet, TextStyle } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        width: '100%',
        height: '100%',
        backgroundColor: '#EDEDEA',
        justifyContent: 'center',
        flexDirection: 'column',
    },
    header: {
        // position: 'absolute',
        // top: 52,
        top: 0,
        backgroundColor: 'white',
        width: '100%',
        // height: 56,
        height: 120,
        justifyContent: 'space-between',
        flexDirection: 'row',
        paddingRight: 16,
        paddingLeft: 16,
        zIndex: 1,
    },
    scrollContainer: {
        width: '100%',
        height: '100%',
        backgroundColor: '#EDEDEA',
    },
    Flex: {
        flex: 1,
        width: 'auto',
        height: 40,
        justifyContent: 'flex-end',
        alignItems: 'center',
        flexDirection: 'row',
        marginTop: 8,
    },
    profileImage: {
        width: 80,
        height: 80,
        objectFit: 'cover',
        marginTop: 8,
        borderRadius: 40,
    },
    IconImage: {
        width: 35,
        height: 35,
        objectFit: 'contain',
        marginLeft: 12,
    },
    myInnerContainer: {
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        paddingLeft: 32,
        paddingRight: 32,
        borderRadius: 30,
    },
    myIconImage: {
        width: 37.09,
        height: 30,
        marginBottom: 12,
        objectFit: 'contain',
    },
    ProfileContainer: {
        backgroundColor: 'white',
        width: '100%',
        height: 300,
        flexDirection: 'column',
        paddingLeft: 14,
        paddingRight: 14,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        zIndex: 2,
        marginTop: -20,
    },
    ProfilePositionContainer: {
        width: '100%',
        paddingTop: 20,
    },
    ProfileImageContainer: {
        width: '100%',
        alignItems: 'center',
        paddingBottom: 24,
        //상위 컨테이너가 column 방향으로 되어있기 때문에  가운데 정렬을 하려면
    },
    ProfileInnerContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingLeft: 14,
        paddingRight: 14,
    },
    myWrittingContainer: {
        top: -50,
        width: '92%',
        height: 114,
        justifyContent: 'space-around',
        alignItems: 'center',
        flexDirection: 'row',
        backgroundColor: 'white',
        borderRadius: 15,
        marginLeft: 2,
        marginRight: 2,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.14,
        shadowRadius: 6.27,
        zIndex: 2,
    },
    scrabImage: {
        width: 26,
        height: 26,
    },
    scrabContainer: {
        top: -40,
        width: '92%',
        height: 162,
        justifyContent: 'space-around',
        flexDirection: 'column',
        backgroundColor: 'white',
        borderRadius: 15,
        paddingVertical: 10,
        paddingLeft: 20,
        paddingRight: 16,
        zIndex: 2,
    },
    bottomContainer: {
        top: -30,
        width: '92%',
        height: 60,
        justifyContent: 'space-around',
        flexDirection: 'column',
        backgroundColor: 'white',
        borderRadius: 15,
        paddingVertical: 10,
        paddingLeft: 20,
        paddingRight: 16,
        zIndex: 2,
    },
    complaintContainer: {
        width: '92%',
        height: 44,
        justifyContent: 'space-around',
        flexDirection: 'column',
        backgroundColor: 'white',
        borderRadius: 15,
        paddingVertical: 10,
        paddingLeft: 20,
        paddingRight: 16,
        zIndex: 2,
        bottom: 15,
    },
    allowIconImage: {
        width: 40,
        height: 20,
    },
    bottomInfoContainer: {
        height: 20,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 30,
    },
    foraContainer: {
        marginTop: 10,
        width: '90%',
        marginBottom: 30,
    },
    bottomInfoForaImage: {
        width: 90,
        height: 45,
        objectFit: 'contain',
        marginBottom: 20,
    },
    bottomInfoIconImage: {
        width: 70,
        height: 26,
        objectFit: 'contain',
        marginVertical: 30,
    },
});

const baseText = {
    fontFamily: 'Pretendard',
    fontStyle: 'normal',
    fontWeight: '400',
};

export const text = {
    headerText: {
        color: '#232323',
        fontSize: 24,
        fontWeight: 'bold',
        letterSpacing: -1,
        top: 70,
    },
    nickName: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#232323',
    },
    sirText: {
        ...baseText,
        color: '#232323',
        fontSize: 24,
        letterSpacing: -0.7,
    },
    emailText: {
        ...baseText,
        color: '#949494',
        fontSize: 16,
        letterSpacing: -0.7,
    },
    myText: {
        ...baseText,
        fontSize: 18,
        textAlign: 'center',
    },
    commonText: {
        ...baseText,
        fontSize: 18,
        letterSpacing: -0.5,
    },
    bottomTextBold: {
        fontWeight: '600',
        fontSize: 12,
        color: '#555555',
        letterSpacing: -0.6,
        lineHeight: 16.8,
    },
    bottomTextNormal: {
        ...baseText,
        fontSize: 12,
        color: '#555555',
        letterSpacing: -0.6,
        lineHeight: 16.8,
    },
    bottomInfoVector: {
        ...baseText,
        marginHorizontal: 9,
        fontSize: 17,
        color: '#949494',
        letterSpacing: -0.6,
    },
} as {
    [key: string]: StyleProp<TextStyle>;
};
