import { StyleProp, StyleSheet, TextStyle } from 'react-native'

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: 'white',
        justifyContent: 'center',
        flexDirection: 'column',
    },
    grayContainer: {
        position: 'absolute',
        top: 52,
        backgroundColor: '#EDEDEA',
        width: '100%',
        height: '100%',
        zIndex: 1,
    },
    header: {
        position: 'absolute',
        top: 52,
        backgroundColor: 'white',
        width: '100%',
        height: 36,
        justifyContent: 'space-between',
        flexDirection: 'row',
        paddingRight: 16,
        paddingLeft: 16,
        zIndex: 3,
    },
    Flex: {
        flex: 1,
        width: 'auto',
        height: 40,
        justifyContent: 'flex-end',
        alignItems: 'center',
        flexDirection: 'row',
        marginTop: 8,
    },
    profileImage: {
        width: 80,
        height: 80,
        objectFit: 'cover',
        marginTop: 8,
        borderRadius: 40,
    },
    IconImage: {
        width: 35,
        height: 35,
        objectFit: 'contain',
        marginLeft: 12,
    },
    myInnerContainer: {
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        paddingLeft: 32,
        paddingRight: 32,
        borderRadius: 30,
    },
    myIconImage: {
        width: 37.09,
        height: 30,
        marginBottom: 12,
        objectFit: 'contain',
    },
    ProfileContainer: {
        position: 'absolute',
        top: 87,
        backgroundColor: 'white',
        width: '100%',
        height: 241,
        flexDirection: 'column',
        paddingLeft: 14,
        paddingRight: 14,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        zIndex: 2,
    },
    ProfilePositionContainer: {
        position: 'relative',
        top: 12,
    },
    ProfileImageContainer: {
        width: '100%',
        alignItems: 'center',
        paddingBottom: 24,
        //상위 컨테이너가 column 방향으로 되어있기 때문에  가운데 정렬을 하려면
    },
    ProfileInnerContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingLeft: 14,
        paddingRight: 14,
    },
    myWrittingContainer: {
        position: 'absolute',
        top: 0,
        width: 382,
        height: 114,
        justifyContent: 'space-around',
        alignItems: 'center',
        flexDirection: 'row',
        backgroundColor: 'white',
        borderRadius: 15,
        marginLeft: 2,
        marginRight: 2,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.14,
        shadowRadius: 6.27,
        zIndex: 2,
    },
    scrabImage: {
        width: 26,
        height: 26,
    },
    scrabContainer: {
        position: 'absolute',
        top: 122,
        width: 382,
        height: 152,
        justifyContent: 'space-around',
        flexDirection: 'column',
        backgroundColor: 'white',
        borderRadius: 15,
        paddingLeft: 16,
        paddingRight: 16,
        zIndex: 2,
    },
    bottomContainer: {
        position: 'absolute',
        top: 282,
        width: 382,
        height: 152,
        justifyContent: 'space-around',
        flexDirection: 'column',
        backgroundColor: 'white',
        borderRadius: 15,
        paddingLeft: 16,
        paddingRight: 16,
        zIndex: 2,
    },
    allowIconImage: {
        width: 40,
        height: 20,
    },
})

const baseText = {
    fontFamily: 'Pretendard',
    fontStyle: 'normal',
    fontWeight: '400',
}

export const text = {
    headerText: {
        color: '#232323',
        fontSize: 24,
        fontWeight: 'bold',
        letterSpacing: -1,
    },
    nickName: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#232323',
    },
    sirText: {
        ...baseText,
        color: '#232323',
        fontSize: 24,
        letterSpacing: -0.7,
    },
    emailText: {
        ...baseText,
        color: '#949494',
        fontSize: 16,
        letterSpacing: -0.7,
    },
    myText: {
        ...baseText,
        fontSize: 18,
        textAlign: 'center',
    },
    commonText: {
        ...baseText,
        fontSize: 18,
        letterSpacing: -0.5,
    },
} as {
    [key: string]: StyleProp<TextStyle>
}
