import { StyleProp, StyleSheet, TextStyle } from 'react-native'

//자주 반복되는 색 객체로 빼서 사용
const color = {
    primary: '#52A35D',
    inactive: '#555555',
    ribbon: '#FF5D5D',
    normal: '#232323',
    active: '#FF5D5D',
    background: '#F4F9D9',
    cancel: '#EEEEEE',
    InactiveBackground: '#949494',
}
const baseText = {
    fontFamily: 'Pretendard',
    fontStyle: 'normal',
    fontWeight: '400',
}
export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        justifyContent: 'center',
        flexDirection: 'column',
        width: '100%',
        alignItems: 'center',
    },
    finishContainer: {
        width: '100%',
        height: '100%',
        position: 'absolute',
        top: 0,
        zIndex: 10,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        opacity: 10,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'column',
    },
    modalContainer: {
        width: 364,
        height: 153,
        zIndex: 10,
        justifyContent: 'center',
        flexDirection: 'column',
        borderRadius: 12,
        overflow: 'hidden', //자식 컴포넌트의 테두리가 보여서 설정
    },
    thanksContainer: {
        width: '100%',
        height: '67%',
        position: 'absolute',
        top: 0,
        backgroundColor: 'white',
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'column',
    },
    homeContainer: {
        width: '100%',
        height: '33%',
        position: 'absolute',
        bottom: 0,
        backgroundColor: color.active,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'column',
    },
    header: {
        position: 'absolute',
        top: 52,
        width: '100%',
        height: 36,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingRight: 16,
        paddingLeft: 16,
        paddingBottom: 14,
        zIndex: 2,
        borderBottomColor: color.active,
        borderBottomWidth: 2,
    },
    highTitleContainer: {
        position: 'absolute',
        top: 220,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        width: '100%',
    },
    lowTitleContainer: {
        position: 'absolute',
        top: 164,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        width: '100%',
    },
    middleContainer: {
        position: 'absolute',
        width: '100%',
        justifyContent: 'center',
    },
    highPosition: {
        top: 570,
    },
    lowPosition: {
        top: 449,
    },
    bottomContainer: {
        position: 'absolute',
        justifyContent: 'center',
        top: 747,
        width: '100%',
    },
    flex: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        marginHorizontal: 16,
        width: 382,
        height: 70,
        borderRadius: 8,
        borderWidth: 1,
        marginBottom: 8,
    },
    active: {
        borderColor: color.active,
        backgroundColor: color.background,
    },
    inactive: {
        borderColor: color.inactive,
    },
    checkImage: {
        width: 20,
        height: 20,
        objectFit: 'contain',
    },
    checkListContainer: {
        position: 'absolute',
        top: 246,
        justifyContent: 'center',
    },
    smallImage: {
        width: 23,
        height: 23,
        objectFit: 'contain',
        marginRight: 4,
    },
    IconImage: {
        width: 24,
        height: 24,
        objectFit: 'contain',
    },
    Ribbons: {
        width: 64,
        height: 12,
        objectFit: 'contain',
    },
    InputContainer: {
        position: 'absolute',
        top: 510,
        width: '92.2%',
        height: 179,
        borderRadius: 8,
        borderWidth: 1,
        padding: 13,
    },
    InputStyles: {
        width: '100%',
        color: color.normal,
        fontSize: 15,
        lineHeight: 24,
        letterSpacing: -0.5,
        fontFamily: 'Pretendard',
    },
    HighScoreImage: {
        width: 205,
        height: 152.01,
        objectFit: 'contain',
    },
    lowScoreImage: {
        width: 177.27,
        height: 167.21,
        objectFit: 'contain',
    },
    cancelContainer: {
        width: 123,
        height: 60,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: color.cancel,
    },
    activeBackground: {
        backgroundColor: color.active,
    },
    inactiveBackground: {
        backgroundColor: color.InactiveBackground,
    },
    ButtonsContainer: {
        backgroundColor: 'white',
        borderTopWidth: 9,
        borderTopColor: color.cancel,
        zIndex: 3,
        paddingHorizontal: 16,
        paddingTop: 20,
        paddingBottom: 34,
        position: 'absolute',
        bottom: 0,
        justifyContent: 'space-between',
        flexDirection: 'row',
        width: '100%',
        height: 111,
    },
    buttonBottomContainer: {
        position: 'absolute',
        bottom: 34,
        width: '100%',
        height: 60,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: color.active,
    },
})

export const text = {
    headerText: {
        color: color.normal,
        fontSize: 18,
        fontWeight: 'bold',
        letterSpacing: -0.7,
        lineHeight: 22.4,
        textAlign: 'center',
        marginLeft: 70,
    },
    lastText: {
        fontWeight: '800',
        fontSize: 18,
        lineHeight: 24,
        color: color.normal,
    },
    inputCountText: {
        ...baseText,
        color: color.normal,
        fontSize: 14,
        lineHeight: 30,
        position: 'absolute',
        bottom: 0,
        right: 0,
    },
    hospitalText: {
        fontWeight: '800',
        fontSize: 20,
        lineHeight: 30,
        color: color.active,
    },
    questionText: {
        fontWeight: '800',
        fontSize: 20,
        lineHeight: 28,
        color: 'black',
    },
    middleText: {
        ...baseText,
        fontSize: 18,
        lineHeight: 26,
        letterSpacing: -0.5,
        color: color.normal,
        textAlign: 'center',
    },
    bottomText: {
        ...baseText,
        fontSize: 14,
        lineHeight: 19.6,
        letterSpacing: -0.5,
        color: color.InactiveBackground,
        textAlign: 'center',
    },
    cancelText: {
        fontWeight: '700',
        fontSize: 18,
        lineHeight: 24,
        color: color.normal,
    },
    bottomButtonText: {
        fontWeight: '700',
        fontSize: 18,
        lineHeight: 24,
        color: 'white',
    },
} as {
    [key: string]: StyleProp<TextStyle>
}
